### ISSUE TITLE
Question: can I use it for organization projects?

### ISSUE THREAD

**Issue by fgriberi** [peter-evans/repository-dispatch#8] opened 2020-03-17 12:12 UTC
Hi, I was wondering if this action can be used from an organization repository. According to documentation, the repository attribute should be something like: `username/my-repo`. I tried with an organization (`organization/repo-b`, using a personal token) and the event is never caught by the `repo-b`.  I have used branches for testing purposes.
Any suggestion?

**Comment by peter-evans** [comment] 2020-03-17 13:16
@fgriberi Yes, you should be able to use this with organization repositories. The problem is likely that you are trying to test this in a branch. That will not work. The `repository_dispatch` workflow *must* be committed to `master` (or the default branch if it's not `master`) in order for it to trigger.

**Comment by jspiro** [comment] 2020-03-23 04:13
Works in orgs given the above caveat.

**Comment by peter-evans** [comment] 2020-03-23 04:19
@jspiro By "caveat," are you referring to the fact that the `repository_dispatch` workflow must be committed to the default branch? That is the case regardless of whether it's an organization repository or not. There is no usage difference for organization repositories.

**Comment by jspiro** [comment] 2020-03-23 04:20
Yes, I was just +1ing you from direct experience so this issue could be resolved :-)

We have been developing on a secondary clone of our repos before bringing the workflows to the main repo.

**Comment by peter-evans** [comment] 2020-03-23 04:23
Got it. Thanks for confirming!

@fgriberi I'll close this issue now. There is already a comment in the README about committing the workflow to the default branch.

**Closed by peter-evans** 2020-03-23 04:23 UTC
